pybo/views/answer_views.py
# pybo/views/answer_views.py
from flask import Blueprint, url_for, request, render_template
from werkzeug.utils import redirect

from .auth_views import login_required
from ..forms import AnswerForm
from pybo.service.qna_service import QnaService

bp = Blueprint('answer', __name__, url_prefix='/answer')

qna_service = QnaService()


@bp.route('/create/<int:question_id>', methods=('GET', 'POST'))
@login_required
def create(question_id):
    form = AnswerForm()
    question = qna_service.get_question_detail(question_id)

    if form.validate_on_submit():
        content = request.form['content']
        qna_service.create_answer(question_id, content)
        return redirect(url_for('question.detail', question_id=question_id))

    return render_template(
        'question/question_detail.html',
        question=question,
        form=form,
    )

pybo/views/question_views.py
from flask import Blueprint, render_template, request, url_for, g, flash
from werkzeug.utils import redirect

from ..forms import QuestionForm, AnswerForm
from pybo.views.auth_views import login_required
from pybo.service.qna_service import QnaService

bp = Blueprint('question', __name__, url_prefix='/question')

qna_service = QnaService()

# 질문 목록
@bp.route('/list/')
def _list():
    page = request.args.get('page', type=int, default=1)
    question_list = qna_service.get_question_list(page=page, per_page=10)

    return render_template('question/qna.html', question_list=question_list)

# 질문 상세
@bp.route('/detail/<int:question_id>/')
def detail(question_id):
    question = qna_service.get_question_detail(question_id)
    form = AnswerForm()
    return render_template('question/question_detail.html',
                           question=question, form=form)


# 질문 작성
@bp.route('/create/', methods=('GET', 'POST'))
@login_required
def create():
    form = QuestionForm()
    if request.method == 'POST' and form.validate_on_submit():
        qna_service.create_question_from_form(form)
        return redirect(url_for('question._list'))

    return render_template('question/question_form.html', form=form)

#질문 삭제
@bp.route('/delete/<int:question_id>/')
@login_required
def delete(question_id):
    question = qna_service.get_question_detail(question_id)

    # 권한 체크
    if not qna_service.can_edit_or_delete(question, g.user):
        flash('삭제 권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=question_id))

    qna_service.delete_question(question)
    return redirect(url_for('question._list'))

# 질문 수정
@bp.route('/modify/<int:question_id>/', methods=('GET', 'POST'))
@login_required
def modify(question_id):
    question = qna_service.get_question_detail(question_id)

    # 작성자 아니고 관리자도 아니면 막기
    if not qna_service.can_edit_or_delete(question, g.user):
        flash('수정 권한이 없습니다.')
        return redirect(url_for('question.detail', question_id=question_id))

    form = QuestionForm(obj=question)  # 기존 내용 폼에 채워 넣기

    if request.method == 'POST' and form.validate_on_submit():
        qna_service.update_question_from_form(question, form)
        return redirect(url_for('question.detail', question_id=question_id))

    return render_template('question/question_form.html', form=form)

pybo/templates/question/qna.html
{% extends 'base.html' %}

{% block body_class %}hero-page{% endblock %}

{% block content %}

<section class="hero-section hero-qna">
  <div class="hero-overlay"></div>
  <div class="container hero-inner">
    <h1 class="hero-title">Q&A</h1>
  </div>
</section>

<div class="container mt-4 mb-5">

    <div class="card">
        <div class="card-body">

            <div class="d-flex justify-content-between align-items-center mb-3">
                <h4 class="mb-0">Q&A</h4>
                <a href="{{ url_for('question.create') }}" class="btn btn-primary btn-sm">
                    질문 등록하기
                </a>
            </div>

            <table class="table">
                <thead>
                <tr class="thead-dark">
                    <th>번호</th>
                    <th>제목</th>
                    <th>작성자</th>
                    <th>작성일시</th>
                </tr>
                </thead>
                <tbody>
                {% if question_list %}
                    {% for question in question_list.items %}
                    <tr>
                        <!-- 번호 -->
                        <td>
                            {{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}
                        </td>

                        <!-- 제목 -->
                        <td>
                            <a href="{{ url_for('question.detail', question_id=question.id) }}">
                                {{ question.subject }}
                            </a>
                            {% if question.answer_set|length > 0 %}
                            <span class="text-danger small ml-2">
                                {{ question.answer_set|length }}
                            </span>
                            {% endif %}
                        </td>

                        <!-- 작성자 -->
                        <td>
                            {% if question.user %}
                                {{ question.user.username }}
                            {% else %}
                                익명
                            {% endif %}
                        </td>

                        <!-- 작성일시 -->
                        <td>{{ question.create_date }}</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="4">질문이 없습니다.</td>
                    </tr>
                {% endif %}
                </tbody>
            </table>

            <ul class="pagination justify-content-center">

                {# 이전 버튼 #}
                {% if question_list.has_prev %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                </li>
                {% endif %}

                {# 번호들 #}
                {% for page_num in question_list.iter_pages() %}
                    {% if page_num %}
                        {% if page_num != question_list.page %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                            </li>
                        {% else %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#">{{ page_num }}</a>
                        </li>
                        {% endif %}
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link" href="#">...</a>
                    </li>
                    {% endif %}
                {% endfor %}

                {# 다음 버튼 #}
                {% if question_list.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                </li>
                {% endif %}
            </ul>

        </div>
    </div>

</div>
{% endblock %}

pybo/templates/question/question_detail.html
{# templates/question/question_detail.html #}
{% extends 'base.html' %}

{% block content %}

<section class="hero-section hero-qna">
  <div class="hero-overlay"></div>
  <div class="container hero-inner">
    <h1 class="hero-title">Q&A</h1>
  </div>
</section>


<div class="container my-3">

    <h2 class="border-bottom py-2">{{ question.subject }}</h2>

    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ question.content }}
            </div>
            <div class="text-end mt-2">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>

    <div class="mb-3 text-end">
    {% if g.user and (g.user.id == question.user_id or g.user.is_admin) %}
        <a href="{{ url_for('question.modify', question_id=question.id) }}"
           class="btn btn-sm btn-outline-secondary">수정</a>
        <a href="{{ url_for('question.delete', question_id=question.id) }}"
           class="btn btn-sm btn-outline-danger"
           onclick="return confirm('정말 삭제하시겠습니까?');">삭제</a>
    {% endif %}
    </div>

    <h5 class="border-bottom my-3 py-2">
        {{ question.answer_set|length }} 개의 답변이 있습니다.
    </h5>

    {% for answer in question.answer_set %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">
                {{ answer.content }}
            </div>
            <div class="text-end mt-2">
                <div class="badge bg-light text-dark p-2">
                    {% if question.user %}
                        {{ question.user.username }} |
                    {% else %}
                        익명 |
                    {% endif %}
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

    <form action="{{ url_for('answer.create', question_id=question.id) }}"
          method="post" class="my-3">
        {{ form.csrf_token }}
        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ','.join(errors) }}
        </div>
        {% endfor %}

        <div class="form-group">
            <textarea name="content" id="content"
                      class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary mt-2">
    </form>

</div>
{% endblock %}

pybo/templates/question/question_form.html
{# templates/question/question_form.html #}
{% extends 'base.html' %}

{% block content %}

<section class="hero-section hero-qna">
  <div class="hero-overlay"></div>
  <div class="container hero-inner">
    <h1 class="hero-title">Q&A</h1>
  </div>
</section>


<div class="container my-3">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>

    <form method="post" class="post-form my-3">
        {{ form.csrf_token }}

        {% for field, errors in form.errors.items() %}
        <div class="alert alert-danger" role="alert">
            <strong>{{ form[field].label }}</strong>: {{ ','.join(errors) }}
        </div>
        {% endfor %}

        <div class="form-group mb-3">
            <label for="subject">제목</label>
            <input type="text"
                   class="form-control"
                   name="subject" id="subject"
                   value="{{ form.subject.data or '' }}">
        </div>

        <div class="form-group mb-3">
            <label for="content">내용</label>
            <textarea name="content" id="content"
                      rows="10" class="form-control">
{{ form.content.data or '' }}</textarea>
        </div>

        <button type="submit" class="btn btn-primary mt-2">저장하기</button>
    </form>
</div>
{% endblock %}

pybo/templates/question/question_list.html
{# templates/question/question_list.html #}
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">

    <h5 class="my-3 border-bottom pb-2">질문 목록</h5>

    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성자</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
            {% for question in question_list.items %}
            <tr>
                <td>{{ question_list.total - ((question_list.page-1) * question_list.per_page) - loop.index0 }}</td>
                <td>
                    <a href="{{ url_for('question.detail', question_id=question.id) }}">
                        {{ question.subject }}
                    </a>
                    {% if question.answer_set|length > 0 %}
                    <span class="text-danger small ml-2">
                        {{ question.answer_set|length }}
                    </span>
                    {% endif %}
                </td>
                <td>
                    {% if question.user %}
                        {{ question.user.username }}
                    {% else %}
                        익명
                    {% endif %}
                </td>
                <td>{{ question.create_date }}</td>
            </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="4">질문이 없습니다.</td>
            </tr>
        {% endif %}
        </tbody>
    </table>

    {# 페이지네이션 #}
    <ul class="pagination justify-content-center">

        {# 이전 버튼 #}
        {% if question_list.has_prev %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.prev_num }}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}

        {# 번호들 #}
        {% for page_num in question_list.iter_pages() %}
            {% if page_num %}
                {% if page_num != question_list.page %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a>
                </li>
                {% else %}
                <li class="page-item active" aria-current="page">
                    <a class="page-link" href="#">{{ page_num }}</a>
                </li>
                {% endif %}
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#">...</a>
            </li>
            {% endif %}
        {% endfor %}

        {# 다음 버튼 #}
        {% if question_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ question_list.next_num }}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>

    <a href="{{ url_for('question.create') }}" class="btn btn-primary">질문 등록하기</a>
</div>
{% endblock %}